### ISSUE TITLE
`text-stub-library`: upgrade to `serde-yaml` 0.9?

### ISSUE THREAD

**Issue by messense** [indygreg/toolchain-tools#4]
https://github.com/dtolnay/serde-yaml/issues/147 has been resolved in `serde-yaml` 0.9.

https://github.com/indygreg/toolchain-tools/blob/da120d602171ce00cdad7e9495662a1844549167/text-stub-library/src/lib.rs#L75-L82

**Comment by indygreg** [comment]
I just published `text-stub-library` 0.9 using latest crate versions.

I still retained the old hacky parsing code because I didn't feel like refactoring at this time.
